"""empty message

Revision ID: d5b01f593f08
Revises: 4bc542221a52
Create Date: 2016-01-02 14:51:21.121368

"""

# revision identifiers, used by Alembic.
revision = 'd5b01f593f08'
down_revision = '4bc542221a52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary_split', sa.Boolean(), nullable=True))
        batch_op.create_index('primary_split_uix', ['transaction_id', 'is_primary_split'], unique=True, sqlite_where=sa.text(u'is_primary_split != 0'), postgresql_where=sa.text(u'is_primary_split != 0'))
        batch_op.create_unique_constraint('transaction_splits_tran_acc_uix', ['transaction_id', 'account_id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_splits_tran_acc_uix', type_='unique')
        batch_op.drop_index('primary_split_uix')
        batch_op.drop_column('is_primary_split')

    ### end Alembic commands ###
